---
# Use Ansible to create required AWS infrastructure (but not the VPC and 3x private subnets)
# https://docs.openshift.com/container-platform/4.4/installing/installing_aws/installing-aws-user-infra.html

- name: Ensure AWS_PROFILE and AWS_REGION environment vars are set
  assert:
    that:
      - "lookup('env','AWS_PROFILE')"
      - "lookup('env','AWS_DEFAULT_REGION')"
    fail_msg: |
      ERROR: AWS_PROFILE and/or AWS_DEFAULT_REGION was not defined.
      Please correct this by running the commands below and trying again...
      `export AWS_PROFILE=example` and `export AWS_DEFAULT_REGION=us-example-1`


# - import_tasks: vpc_info.yml
- import_tasks: load_balancers_destroy.yml
- import_tasks: instances_destroy.yml
#- import_tasks: iam_roles_destroy.yml
- import_tasks: security_groups_destroy.yml
- import_tasks: keypair_destroy.yml
- import_tasks: vpc_destroy.yml
- import_tasks: route53_destroy.yml
  tags: [route53]
  