---

- name: Skip IAM roles/profiles section
  debug:
    msg: |
      ALERT: This section has not been built yet!

      At this time the OpenShift cluster being deployed will not enable
      the AWS integrations such as:
        * Creating a machineset for auto-scaling the cluster
        * Automatically creating and updating Load Balancers
        * Enabling a default "gp2" storageClass
  # failed_when: true
  # ignore_errors: true