---

- name: "Query instances with tag \"OpenShiftClusterId: {{ cluster_id }}\""
  ec2_instance_info:
    filters:
      tag:OpenShiftClusterId: "{{ cluster_id }}"
      instance-state-name: [ "pending", "running", "shutting-down", "stopping", "stopped" ]
  register: r_query_instances

- name: Build list of instances that will be terminated
  set_fact:
    terminate_list: "{{ terminate_list|default([]) + [ item.tags.Name + '  ' + item.instance_id + '  ' + item.state.name ] }}"
  loop: "{{ r_query_instances.instances }}"
  no_log: true

- name: Print instance termination list
  debug: var=terminate_list

- name: "Remove instances with tag \"OpenShiftClusterId: {{ cluster_id }}\""
  ec2_instance:
    filters:
      tag:OpenShiftClusterId: "{{ cluster_id }}"
      instance-state-name: [ "pending", "running", "shutting-down", "stopping", "stopped" ]
    wait: yes   # wait for this to finish so that the security groups can be disassociated
    state: absent
