---

# # elb_network_lb_info doesn't exist!  (need to create GitHub issue)
# # Do it the hard way via AWS CLI... (which doesn't report tags!!!)
# - name: Query network load balancers
#   command: aws elbv2 describe-load-balancers --output=json
#   when: api_nlb_name is not defined
#   register: r_query_network_lb
- name: Deleting the network load balancers that we created
  elb_network_lb:
    state: absent
    name: "{{ item }}"
  loop:
    - "{{ cluster_id }}-api"
    - "{{ cluster_id }}-app"
  when:
    - api_nlb_name is not defined
    - app_nlb_name is not defined

#TODO: remove our listeners from load balancers we didn't create

# elb_target_group_info doesn't support filters:  (need to create GitHub issue)
- name: Query target groups
  elb_target_group_info:
  register: r_query_target_groups

- name: Remove target groups with matching tags
  elb_target_group:
    state: absent
    name: "{{ item.target_group_name }}"
    protocol: "{{ item.protocol }}"
    port: "{{ item.port }}"
    vpc_id: "{{ item.vpc_id }}"
  loop: "{{ r_query_target_groups.target_groups }}"
  when: item.tags.OpenShiftClusterId == "{{ cluster_id }}"
