---

- name: Query the existing DNS records
  route53:
    state:  get
    private_zone: no
    zone:   "{{ route53_hosted_zone.Name | default(route53_default_hosted_zone_name) }}"
    record: "{{ item.record }}"
    type:   "{{ item.type }}"
  loop:
    - { record: "api.{{ cluster_name }}.{{ base_domain }}",     type: "CNAME" }
    - { record: "api-int.{{ cluster_name }}.{{ base_domain }}", type: "CNAME" }
    - { record: "*.apps.{{ cluster_name }}.{{ base_domain }}",  type: "CNAME" }
    - { record: "etcd-0.{{ cluster_name }}.{{ base_domain }}",  type: "A" }
    - { record: "etcd-1.{{ cluster_name }}.{{ base_domain }}",  type: "A" }
    - { record: "etcd-2.{{ cluster_name }}.{{ base_domain }}",  type: "A" }
    - { record: "_etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }}", type: "SRV" }
  register: r_dns

- debug: var=r_dns

- name: Remove the DNS records
  route53:
    state:  absent
    private_zone: no
    zone:   "{{ item.set.zone }}"
    record: "{{ item.set.record }}"
    ttl:    "{{ item.set.ttl }}"
    type:   "{{ item.set.type }}"
    value:  "{{ item.set.value }}"
  loop: "{{ r_dns.results }}"
  when: item.set.value is defined
