---

- name: Prepare the SRV record value
  set_fact:
    etcd_srv:
      - "0 10 2380 etcd-0.{{ cluster_name }}.{{ base_domain }}."
      - "0 10 2380 etcd-1.{{ cluster_name }}.{{ base_domain }}."
      - "0 10 2380 etcd-2.{{ cluster_name }}.{{ base_domain }}."

- name: Create the DNS records
  route53:
    state:  present
    zone:   "{{ route53_hosted_zone.Name }}"
    private_zone: no
    record: "{{ item.record }}"
    value:  "{{ item.value }}"
    type:   "{{ item.type }}"
    ttl:    "{{ item.ttl }}"   
  loop:
    - { record: "api.{{ cluster_name }}.{{ base_domain }}",     type: "CNAME", ttl: "60", value: "{{ api_nlb_dns_name }}" }
    - { record: "api-int.{{ cluster_name }}.{{ base_domain }}", type: "CNAME", ttl: "60", value: "{{ api_nlb_dns_name }}" }
    - { record: "*.apps.{{ cluster_name }}.{{ base_domain }}",  type: "CNAME", ttl: "60", value: "{{ app_nlb_dns_name }}" }
    - { record: "etcd-0.{{ cluster_name }}.{{ base_domain }}",  type: "A", ttl: "60", value: "{{ r_masters_info.instances.0.private_ip_address }}" }
    - { record: "etcd-1.{{ cluster_name }}.{{ base_domain }}",  type: "A", ttl: "60", value: "{{ r_masters_info.instances.1.private_ip_address }}" }
    - { record: "etcd-2.{{ cluster_name }}.{{ base_domain }}",  type: "A", ttl: "60", value: "{{ r_masters_info.instances.2.private_ip_address }}" }
    - { record: "_etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }}", type: "SRV", ttl: "60", value: "{{ etcd_srv | join(',') }}" }

#TODO: Make a private hosted zone for the `api-int`, SRV, and `etcd-*...` records
####install these records in the PUBLIC hosted zone
# api.{{ cluster_name }}.{{ base_domain }}     CNAME  {{ api_nlb_dns_name }}
# *.apps.{{ cluster_name }}.{{ base_domain }}  CNAME  {{ app_nlb_dns_name }}

####install these records in the PRIVATE hosted zone
# api.{{ cluster_name }}.{{ base_domain }}     CNAME  {{ api_nlb_dns_name }}
# *.apps.{{ cluster_name }}.{{ base_domain }}  CNAME  {{ app_nlb_dns_name }}
# api-int.{{ cluster_name }}.{{ base_domain }} CNAME  {{ api_nlb_dns_name }}
# etcd-0.{{ cluster_name }}.{{ base_domain }}    A    {{ r_masters_info.instances.0.private_ip_address }}
# etcd-1
# etcd-2
# _etcd-server-ssl._tcp.{{ cluster_name }}.{{ base_domain }}   SRV   0 10 2380 "etcd-0.{{ cluster_name }}.{{ base_domain }}."