---

- name: Set boolean to destroy VPC
  set_fact:
    destroy_vpc: yes
  when: vpc_id is undefined

- name: Capture availability zone info
  aws_az_info: {}
  register: r_az_info

- block:
    - name: Capture VPC info
      ec2_vpc_net_info:
        filters:
          tag:Name: "{{ cluster_id }}"
          tag:OpenShiftCluster: "{{ cluster_domain }}"
          tag:OpenShiftClusterId: "{{ cluster_id }}"
      register: r_vpc_info

    - name: Set VPC ID
      set_fact:
        vpc_id: "{{ r_vpc_info.vpcs.0.vpc_id }}"
  when: vpc_id is undefined

- block:
    - name: Capture public hosted zone details
      route53_info:
        hosted_zone_id: "{{ route53_hosted_zone_id }}"
        hosted_zone_method: details
        query: hosted_zone
      register: r_capture_public_hosted_zone

    - name: Set hosted zone name
      set_fact:
        route53_hosted_zone_name: "{{ r_capture_public_hosted_zone.HostedZone.Name }}"
  when: route53_hosted_zone_id is defined

- name: Capture public DNS entries
  route53:
    zone: "{{ route53_hosted_zone_name }}"
    record: "{{ item.record }}.{{ cluster_domain }}"
    type: "{{ item.type }}"
    private_zone: no
    state: get
  loop:
    - record: api
      type: CNAME
    - record: "*.apps"
      type: CNAME
  register: r_capture_public_dns_records

- name: Destroy public DNS entries
  route53:
    zone: "{{ route53_hosted_zone_name }}"
    record: "{{ item.set.record }}"
    value: "{{ item.set.value }}"
    type: "{{ item.set.type }}"
    ttl: "{{ item.set.ttl }}"
    state: absent
  loop: "{{ r_capture_public_dns_records.results }}"
  when: item.set.value is defined

- name: Capture private DNS entries
  route53:
    zone: "{{ cluster_domain }}"
    record: "{{ item.record }}.{{ cluster_domain }}"
    type: "{{ item.type }}"
    private_zone: yes
    state: get
  loop:
    - record: api
      type: CNAME
    - record: api-int
      type: CNAME
    - record: "*.apps"
      type: CNAME
    - record: etcd-0
      type: A
    - record: etcd-1
      type: A
    - record: etcd-2
      type: A
    - record: _etcd-server-ssl._tcp
      type: SRV
  register: r_capture_private_dns_records
  ignore_errors: yes

- name: Destroy private DNS entries
  route53:
    zone: "{{ cluster_domain }}"
    record: "{{ item.set.record }}"
    value: "{{ item.set.value }}"
    type: "{{ item.set.type }}"
    ttl: "{{ item.set.ttl }}"
    private_zone: yes
    state: absent
  loop: "{{ r_capture_private_dns_records.results }}"
  when: item.set.value is defined

- name: Destroy private DNS zone
  route53_zone:
    zone: "{{ cluster_domain }}"
    vpc_id: "{{ vpc_id }}"
    vpc_region: "{{ r_az_info.availability_zones.0.region_name }}"
    state: absent

- name: Destroy load balancers
  elb_network_lb:
    name: "{{ item }}"
    wait: yes
    state: absent
  loop:
    - "{{ cluster_id }}-int"
    - "{{ cluster_id }}-ext"
    - "{{ cluster_id }}-ingress"

- name: Capture target groups
  elb_target_group_info:
    names:
      - "{{ elb_target_group_name_api }}"
      - "{{ elb_target_group_name_api_int }}"
      - "{{ elb_target_group_name_machine_config }}"
      - "{{ elb_target_group_name_http }}"
      - "{{ elb_target_group_name_https }}"
  register: r_capture_target_groups

- name: Destroy target groups
  elb_target_group:
    name: "{{ item.target_group_name }}"
    vpc_id: "{{ item.vpc_id }}"
    protocol: "{{ item.protocol }}"
    port: "{{ item.port }}"
    wait: yes
    state: absent
  loop: "{{ r_capture_target_groups.target_groups }}"

- name: Destroy EC2 instances
  ec2_instance:
    filters:
      tag:OpenShiftCluster: "{{ cluster_domain }}"
      tag:OpenShiftClusterId: "{{ cluster_id }}"
      instance-state-name: ["pending", "running", "shutting-down", "stopping", "stopped"]
    wait: yes
    state: absent

- name: Capture security groups
  ec2_group_info:
    filters:
      tag:OpenShiftCluster: "{{ cluster_domain }}"
      tag:OpenShiftClusterId: "{{ cluster_id }}"
  register: r_catpure_security_groups

- name: Purge all security group rules
  ec2_group:
    group_id: "{{ item.group_id }}"
    name: "{{ item.group_name }}"
    description: "{{ item.description }}"
    vpc_id: "{{ vpc_id }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules:
      - rule_desc: Dummy rule to replace all other rules
        proto: icmp
        ports: 0
        cidr_ip: 169.254.0.0/16
  loop: "{{ r_catpure_security_groups.security_groups }}"

- name: Destroy security groups
  ec2_group:
    group_id: "{{ item.group_id }}"
    vpc_id: "{{ vpc_id }}"
    state: absent
  loop: "{{ r_catpure_security_groups.security_groups }}"

- block:
    - name: Capture NAT gateways
      ec2_vpc_nat_gateway_info:
        filters:
          tag:OpenShiftCluster: "{{ cluster_domain }}"
          tag:OpenShiftClusterId: "{{ cluster_id }}"
      register: r_capture_nat_gateways

    - name: Destroy NAT gateways
      ec2_vpc_nat_gateway:
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        release_eip: yes
        wait: yes
        state: absent
      loop: "{{ r_capture_nat_gateways.result }}"

    - name: Capture subnets
      ec2_vpc_subnet_info:
        filters:
          vpc-id: "{{ vpc_id }}"
          tag:OpenShiftCluster: "{{ cluster_domain }}"
          tag:OpenShiftClusterId: "{{ cluster_id }}"
      register: r_capture_subnets

    - name: Destroy subnets
      ec2_vpc_subnet:
        vpc_id: "{{ vpc_id }}"
        az: "{{ item.availability_zone }}"
        cidr: "{{ item.cidr_block }}"
        tags:
          OpenShiftCluster: "{{ cluster_domain }}"
          OpenShiftClusterId: "{{ cluster_id }}"
        state: absent
      loop: "{{ r_capture_subnets.subnets }}"

    - name: Capture route tables
      ec2_vpc_route_table_info:
        filters:
          vpc-id: "{{ vpc_id }}"
          tag:OpenShiftCluster: "{{ cluster_domain }}"
          tag:OpenShiftClusterId: "{{ cluster_id }}"
      register: r_capture_route_tables

    - name: Destroy route tables
      ec2_vpc_route_table:
        route_table_id: "{{ item.id }}"
        vpc_id: "{{ vpc_id }}"
        lookup: id
        state: absent
      loop: "{{ r_capture_route_tables.route_tables }}"

    - name: Destroy Internet gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id }}"
        tags:
          OpenShiftCluster: "{{ cluster_domain }}"
          OpenShiftClusterId: "{{ cluster_id }}"
        state: absent

    - name: Destroy VPC
      ec2_vpc_net:
        name: "{{ cluster_id }}"
        cidr_block: "{{ vpc_cidr }}"
        tags:
          OpenShiftCluster: "{{ cluster_domain }}"
          OpenShiftClusterId: "{{ cluster_id }}"
        state: absent
  when: destroy_vpc
