---
# tasks file for openshift_install

- name: Check for ignition files
  stat:
    path: "{{ openshift_install_dir }}/bootstrap.ign"
  register: r_stat_ignition_files

- block:
    - name: Create OpenShift installation directory
      file:
        path: "{{ openshift_install_dir }}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0755
        state: directory

    - name: Create OpenShift install-config.yaml
      template:
        src: install-config.yaml.j2
        dest: "{{ openshift_install_dir }}/{{ item }}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0644
      loop:
        - install-config.yaml
        - install-config.backup.yaml

    - name: Generate OpenShift manifests
      command: openshift-install create manifests
      args:
        chdir: "{{ openshift_install_dir }}"

    - name: Mark controllers as not scheduleable
      lineinfile:
        path: "{{ openshift_install_dir }}/manifests/cluster-scheduler-02-config.yml"
        regexp: '^(\s*mastersSchedulable:)'
        line: '\1 false'
        backrefs: yes

    - name: Generate OpenShift ignition configs
      command: openshift-install create ignition-configs
      args:
        chdir: "{{ openshift_install_dir }}"

    - name: Copy OpenShift ignition configs to httpd
      copy:
        src: "{{ openshift_install_dir }}/{{ item }}.ign"
        dest: /var/www/html
        owner: root
        group: root
        mode: 0644
        remote_src: yes
      become: yes
      loop:
        - bootstrap
        - master
        - worker
  when: not r_stat_ignition_files.stat.exists

- name: Wait for OpenShift bootstrap to complete (this may take a while)
  command: openshift-install wait-for bootstrap-complete --log-level=debug
  args:
    chdir: "{{ openshift_install_dir }}"
  async: 3600  # 60 minutes (30 min for api and 30 min for bootstrap)
  poll: 30

- name: Remove bootstrap machine
  ec2_instance:
    instance_ids: "{{ hostvars.bootstrap.instance_id }}"
    state: absent
  delegate_to: localhost
  when: cloud in ['aws', 'aws_govcloud']

- name: Approve CSR requests from worker nodes (5 minute timeout)
  script: "{{ role_path }}/files/csr_approve.sh {{ instance_count_worker }}"
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"

- name: Wait for OpenShift installation to complete (this may take a while)
  command: openshift-install wait-for install-complete --log-level=debug
  args:
    chdir: "{{ openshift_install_dir }}"
  async: 2400  # 40 minutes (30 min for cluster and 10 min for console)
  poll: 30
