---
# tasks file for openshift_install

- name: Check for ignition files
  stat:
    path: "{{ openshift_install_dir }}/install-config.yaml"
  register: r_stat_ignition_files

- block:
    - name: Create OpenShift installation directory
      file:
        path: "{{ openshift_install_dir }}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0755
        state: directory

    - name: Create OpenShift install-config.yaml
      template:
        src: install-config.yaml.j2
        dest: "{{ openshift_install_dir }}/{{ item }}"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0644
      loop:
        - install-config.yaml
        - install-config.backup.yaml
  when: not r_stat_ignition_files.stat.exists

- name: Output cluster information
  debug:
    msg: |
      Your OpenShift 4 infrastructure has finished deploying.

      The cluster consists of the following machines:
        {% for master in terraform_outputs.masters.value %}
        master{{ loop.index0 }}    {{ master.private_ip }}
        {% endfor %}
        {%- for worker in terraform_outputs.workers.value %}
        worker{{ loop.index0 }}    {{ worker.private_ip }}
        {% endfor %}

      If you need to SSH into any of the OpenShift nodes, you can do so from the bastion:
        ssh -i {{ keypair_path }} {{ hostvars['bastion'].ansible_user }}@{{ hostvars['bastion'].ansible_host }}
