---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if a supported cloud has been specified
      fail:
        msg: |-
          You must specify a cloud from the options below:
            - aws
            - aws_govcloud
      when: cloud not in ['aws', 'aws_govcloud']

- hosts: localhost
  tasks:
    - import_role:
        name: infrastructure_aws
        tasks_from: destroy.yml
      tags: [infrastructure]
      when: cloud == 'aws'

# - hosts: localhost
#   tasks:
#     - import_role:
#         name: infrastructure
#         tasks_from: aws_govcloud_destroy
#       tags: [infrastructure]
#       when: cloud == 'aws_govcloud'
